/**:
  ros__parameters:
    input_frame: "base_link"
    output_frame: "base_link"
    min_x: -18.0
    max_x: 18.0
    min_y: -18.0
    max_y: 18.0
    min_z: -2.5
    max_z: 5.0
    negative: False
